GET http://localhost:4000/v1/books

###

GET http://localhost:4000/v1/books/645

###


GET http://localhost:4000/v1/books?genres=fiction

###


GET http://localhost:4000/v1/healthcheck


###

POST http://localhost:4000/v1/books
Content-Type: application/json

{
  "title": "Sapiens: A Brief History of Humankind",
  "year": 2011,
  "pages": 443,
  "genres":["Non-fiction"]
}
###

PUT http://localhost:4000/v1/books/4
Content-Type: application/json

{
  "title": "Sapiens: A Brief History of Humankind",
  "year": 2011,
  "pages": 444,
  "genres":["Non-fiction"]
}
###



DELETE http://localhost:4000/v1/books/3

###

